n = int(input("enter the scores: "))
l1 = list()
for i in range(n):
    scores = int(input("Enter the scores: "))
    l1.append(scores)
l1.sort()
Sum = sum(l1)
Min = min(l1)
Max = max(l1)
Avg = Sum / len(l1)
print(l1)
print(Min)
print(Max)
print(Avg)
